server:
  port: 8088
  servlet:
    context-path: /spring-boot-integration-quartz
spring:
  datasource:
    driver-class-name:  com.mysql.jdbc.Driver
    url:  jdbc:mysql://192.168.88.129:3306/quartz?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: youshang520i
  jpa:
    database: mysql
    show-sql: true
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: top.youshang520i.pojo





